import type { ToolDefinition } from "@/lib/tools/types";
import { CATEGORIES } from "@/lib/tools/types";

const privacy = "Files are processed in your browser for this tool. Nothing is uploaded to our servers unless you later enable a cloud worker.";

function t(partial: ToolDefinition): ToolDefinition {
  return partial;
}

export const TOOLS: ToolDefinition[] = [
  t({
    slug: "merge-pdf",
    name: "Merge PDF",
    h1: "Merge PDF files",
    tagline: "Combine multiple PDFs into one document.",
    description: "Drop two or more PDFs, arrange them, and download a single file. Useful for applications, reports and scanned packets.",
    category: "organize-pdf",
    icon: "Combine",
    accepts: ["pdf"],
    multiple: true,
    minFiles: 2,
    output: "pdf",
    popular: true,
    local: true,
    settings: [],
    related: ["split-pdf", "compress-pdf", "pdf-page-numbering", "watermark-pdf"],
    nextActions: ["compress-pdf", "pdf-page-numbering", "watermark-pdf", "protect-pdf"],
    phrases: ["combine pdf", "join pdf", "put pdfs together", "merge documents"],
    howTo: ["Add at least two PDF files.", "Files are joined in the order shown.", "Process locally in your browser.", "Download the merged PDF, then continue in the workspace."],
    faqs: [
      { q: "Is there a page limit?", a: "Free use is capped for reliability. Very large packets should be merged in groups, then merged again." },
      { q: "Does merge keep bookmarks?", a: "Page content is copied. Interactive extras such as some bookmarks may not survive every merge." },
    ],
    guide: {
      title: "How to merge PDFs",
      paragraphs: [
        "Merging is the fastest way to assemble an application packet, a class reading, or a signed contract plus exhibits. Add files in the order you want them to appear.",
        "After you download, the session workspace keeps the merged file so you can compress it for an upload limit or add page numbers for a print packet.",
        privacy,
      ],
    },
  }),
  t({
    slug: "split-pdf",
    name: "Split PDF",
    h1: "Split a PDF",
    tagline: "Cut a PDF into a page range or one file per page.",
    description: "Keep only the pages you need, or export every page as its own PDF in a ZIP.",
    category: "organize-pdf",
    icon: "Scissors",
    accepts: ["pdf"],
    multiple: false,
    output: "zip",
    popular: true,
    local: true,
    settings: [
      { key: "mode", label: "Split mode", type: "select", defaultValue: "range", options: [{ value: "range", label: "Page range" }, { value: "each", label: "One PDF per page (ZIP)" }] },
      { key: "pages", label: "Pages", type: "text", placeholder: "1-3,5", help: "Used when mode is page range." },
    ],
    related: ["extract-pdf-pages", "delete-pdf-pages", "merge-pdf", "compress-pdf"],
    nextActions: ["compress-pdf", "merge-pdf", "pdf-to-jpg"],
    phrases: ["cut pdf", "separate pages", "split document"],
    howTo: ["Upload one PDF.", "Choose a range or one-file-per-page.", "Process, then download the result or ZIP."],
    faqs: [{ q: "Can I split by bookmarks?", a: "This version splits by page numbers. Use extract if you already know the range." }],
    guide: { title: "How to split a PDF", paragraphs: ["If a portal only accepts the signature page, split is faster than reprinting. For email size limits, split first, then compress the piece you actually need.", privacy] },
  }),
  t({
    slug: "extract-pdf-pages",
    name: "Extract PDF pages",
    h1: "Extract pages from a PDF",
    tagline: "Save a selection of pages as a new PDF.",
    description: "Pull appendix pages, a certificate, or a single form out of a long file.",
    category: "organize-pdf",
    icon: "FileOutput",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "pages", label: "Pages to keep", type: "text", placeholder: "1-2,8", defaultValue: "1" }],
    related: ["split-pdf", "delete-pdf-pages", "merge-pdf"],
    nextActions: ["compress-pdf", "watermark-pdf", "pdf-to-jpg"],
    phrases: ["pull pages out", "save some pages", "extract pages"],
    howTo: ["Upload the PDF.", "Enter pages such as 1-3,7.", "Download the new file."],
    faqs: [{ q: "Does extract delete the original?", a: "No. Your original stays on your device. We never keep a server copy of this tool's files." }],
    guide: { title: "How to extract PDF pages", paragraphs: ["Extraction is the right tool when you need a subset and want a normal PDF, not a ZIP of single pages.", privacy] },
  }),
  t({
    slug: "delete-pdf-pages",
    name: "Delete PDF pages",
    h1: "Delete pages from a PDF",
    tagline: "Remove blank, duplicate or sensitive pages.",
    description: "Drop the pages you do not want to share. At least one page must remain.",
    category: "organize-pdf",
    icon: "FileX",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "pages", label: "Pages to delete", type: "text", placeholder: "2,5-6" }],
    related: ["extract-pdf-pages", "rearrange-pdf-pages", "compress-pdf"],
    nextActions: ["compress-pdf", "protect-pdf"],
    phrases: ["remove pages", "delete blank page"],
    howTo: ["Upload the PDF.", "List pages to remove.", "Download the shorter file."],
    faqs: [{ q: "Can I undo after download?", a: "The original file on your computer is unchanged. The workspace also keeps the last result until it expires." }],
    guide: { title: "How to delete PDF pages", paragraphs: ["Removing a blank scanner page before you email a contract is a typical use. If the remaining file is still large, compress next.", privacy] },
  }),
  t({
    slug: "rearrange-pdf-pages",
    name: "Rearrange PDF pages",
    h1: "Rearrange PDF pages",
    tagline: "Put pages in a new order.",
    description: "Type the order you want, such as 3,1,2,4. The workspace preview helps you confirm page numbers first.",
    category: "organize-pdf",
    icon: "ArrowLeftRight",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "order", label: "New order", type: "text", placeholder: "3,1,2,4" }],
    related: ["rotate-pdf", "merge-pdf", "pdf-page-numbering"],
    nextActions: ["pdf-page-numbering", "watermark-pdf"],
    phrases: ["reorder pages", "move pages around"],
    howTo: ["Upload the PDF.", "Enter the new page order.", "Process and download."],
    faqs: [{ q: "What if I skip a page in the order?", a: "Only listed pages are kept, in that sequence. Include every page you still need." }],
    guide: { title: "How to rearrange PDF pages", paragraphs: ["Scanned packets often land out of order. Rearrange, then add page numbers so reviewers can cite pages.", privacy] },
  }),
  t({
    slug: "rotate-pdf",
    name: "Rotate PDF",
    h1: "Rotate PDF pages",
    tagline: "Fix sideways scans in 90-degree steps.",
    description: "Rotate every page or a range. Rotation is saved into the PDF, not just the viewer.",
    category: "organize-pdf",
    icon: "RotateCw",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    popular: true,
    local: true,
    settings: [
      { key: "angle", label: "Angle", type: "select", defaultValue: "90", options: [{ value: "90", label: "90° clockwise" }, { value: "180", label: "180°" }, { value: "270", label: "90° counter-clockwise" }] },
      { key: "pages", label: "Pages", type: "text", placeholder: "All pages if empty" },
    ],
    related: ["rearrange-pdf-pages", "compress-pdf", "jpg-to-pdf"],
    nextActions: ["compress-pdf", "merge-pdf"],
    phrases: ["turn pdf", "sideways scan", "rotate pages"],
    howTo: ["Upload the PDF.", "Choose an angle and optional page range.", "Download the rotated file."],
    faqs: [{ q: "Will this rotate images inside the page?", a: "It rotates the page box. That's what most printers and portals respect." }],
    guide: { title: "How to rotate a PDF", paragraphs: ["Phone scans of certificates are often landscape. Rotate once, then merge with the rest of an application.", privacy] },
  }),
  t({
    slug: "duplicate-pdf-pages",
    name: "Duplicate PDF pages",
    h1: "Duplicate PDF pages",
    tagline: "Append copies of selected pages.",
    description: "Useful when a form must be filled twice or a cover sheet should appear again at the end.",
    category: "organize-pdf",
    icon: "Copy",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "pages", label: "Pages to duplicate", type: "text", placeholder: "1", defaultValue: "1" }],
    related: ["extract-pdf-pages", "merge-pdf"],
    nextActions: ["pdf-page-numbering", "compress-pdf"],
    phrases: ["copy pages", "duplicate sheet"],
    howTo: ["Upload the PDF.", "Choose pages to copy.", "Copies are appended at the end."],
    faqs: [{ q: "Can I insert duplicates in the middle?", a: "This version appends copies. Use rearrange afterwards if you need a different position." }],
    guide: { title: "How to duplicate PDF pages", paragraphs: ["Duplicating a blank form page is faster than merging a second file.", privacy] },
  }),
  t({
    slug: "reverse-pdf-pages",
    name: "Reverse PDF pages",
    h1: "Reverse PDF page order",
    tagline: "Flip a document last-page-first.",
    description: "Some scanners output pages backwards. One click restores reading order.",
    category: "organize-pdf",
    icon: "ArrowDownUp",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [],
    related: ["rearrange-pdf-pages", "rotate-pdf"],
    nextActions: ["pdf-page-numbering", "compress-pdf"],
    phrases: ["backwards scan", "flip page order"],
    howTo: ["Upload the PDF.", "Process to reverse every page.", "Download the corrected file."],
    faqs: [{ q: "Does reverse keep rotation?", a: "Yes. Only order changes." }],
    guide: { title: "How to reverse PDF pages", paragraphs: ["ADF scanners that feed last-sheet-first are the usual reason to reverse a file.", privacy] },
  }),
  t({
    slug: "pdf-page-numbering",
    name: "PDF page numbering",
    h1: "Add page numbers to a PDF",
    tagline: "Stamp page numbers for print and review.",
    description: "Choose a position and starting number. Numbers are drawn onto the page.",
    category: "organize-pdf",
    icon: "Hash",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [
      { key: "position", label: "Position", type: "select", defaultValue: "bottom-center", options: [
        { value: "bottom-center", label: "Bottom center" },
        { value: "bottom-right", label: "Bottom right" },
        { value: "bottom-left", label: "Bottom left" },
        { value: "top-center", label: "Top center" },
      ] },
      { key: "start", label: "Start at", type: "number", defaultValue: "1" },
    ],
    related: ["add-header", "add-footer", "watermark-pdf"],
    nextActions: ["compress-pdf", "protect-pdf", "sign-pdf"],
    phrases: ["page numbers", "number pages", "pagination"],
    howTo: ["Upload the PDF.", "Pick a position.", "Download the numbered file."],
    faqs: [{ q: "Can I skip the cover?", a: "Number everything, or extract the body, number it, then merge the cover back on." }],
    guide: { title: "How to add page numbers", paragraphs: ["Numbered pages make committee review and student submissions easier to cite.", privacy] },
  }),
  t({
    slug: "add-page-numbers",
    name: "Add page numbers",
    h1: "Add page numbers",
    tagline: "A direct path to pagination.",
    description: "Same engine as PDF page numbering — kept as its own URL because people search this phrase.",
    category: "edit-pdf",
    icon: "Hash",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [
      { key: "position", label: "Position", type: "select", defaultValue: "bottom-center", options: [
        { value: "bottom-center", label: "Bottom center" },
        { value: "bottom-right", label: "Bottom right" },
      ] },
      { key: "start", label: "Start at", type: "number", defaultValue: "1" },
    ],
    related: ["pdf-page-numbering", "add-header", "add-footer"],
    nextActions: ["compress-pdf", "watermark-pdf"],
    phrases: ["add page numbers to pdf"],
    howTo: ["Upload.", "Choose position.", "Download."],
    faqs: [{ q: "Is this different from PDF page numbering?", a: "No — it is the same processor with search-friendly copy." }],
    guide: { title: "Add page numbers to a PDF", paragraphs: ["Use this when you already have a finished document and only need pagination before you send it.", privacy] },
  }),
  t({
    slug: "compress-pdf",
    name: "Compress PDF",
    h1: "Compress a PDF",
    tagline: "Reduce PDF size while keeping it usable.",
    description: "Rebuild large scanned PDFs at a practical quality. If a text PDF is already small, we tell you instead of pretending it shrank.",
    category: "compress-pdf",
    icon: "Minimize2",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    popular: true,
    local: true,
    settings: [
      { key: "quality", label: "Compression", type: "select", defaultValue: "medium", options: [
        { value: "low", label: "Strong (smaller, softer scans)" },
        { value: "medium", label: "Balanced" },
        { value: "high", label: "Light (sharper, larger)" },
      ] },
    ],
    related: ["reduce-pdf-size", "optimize-pdf", "pdf-to-jpg", "merge-pdf"],
    nextActions: ["pdf-to-word", "protect-pdf", "sign-pdf", "watermark-pdf"],
    phrases: ["make pdf smaller", "reduce pdf size", "compress for email"],
    howTo: ["Upload a PDF.", "Choose a compression level.", "Compare sizes, then download."],
    faqs: [
      { q: "Will text stay selectable?", a: "Strong compression rasterizes pages so they behave like scans. Use light compression when you must keep text as text." },
      { q: "Why didn't my file get smaller?", a: "Already-optimized text PDFs often cannot shrink. We keep the smaller result and warn you when size did not drop." },
    ],
    guide: {
      title: "How to compress a PDF",
      paragraphs: [
        "Job portals and government forms often cap uploads at a few megabytes. Compression is the usual fix for phone-scanned certificates.",
        "Pick balanced first. If the file is still too big, use strong compression or split off unused pages.",
        privacy,
      ],
    },
  }),
  t({
    slug: "reduce-pdf-size",
    name: "Reduce PDF size",
    h1: "Reduce PDF file size",
    tagline: "Hit a practical size for uploads.",
    description: "Same compression engine with optional target size in kilobytes. We iterate quality until we get under the target or hit the floor.",
    category: "compress-pdf",
    icon: "Gauge",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [
      { key: "quality", label: "Starting quality", type: "select", defaultValue: "medium", options: [
        { value: "low", label: "Strong" },
        { value: "medium", label: "Balanced" },
        { value: "high", label: "Light" },
      ] },
      { key: "targetKb", label: "Target size (KB)", type: "number", placeholder: "1024" },
    ],
    related: ["compress-pdf", "split-pdf", "pdf-to-jpg"],
    nextActions: ["merge-pdf", "protect-pdf"],
    phrases: ["pdf too large", "under 1mb", "upload limit"],
    howTo: ["Upload the PDF.", "Optionally set a target size in KB.", "Download the smaller file."],
    faqs: [{ q: "Can every file hit 500 KB?", a: "No. A 40-page color scan has a floor. Split pages if you are still over the limit." }],
    guide: { title: "How to reduce PDF size", paragraphs: ["Set the target to whatever the portal states, usually 1024 or 2048 KB.", privacy] },
  }),
  t({
    slug: "optimize-pdf",
    name: "Optimize PDF",
    h1: "Optimize a PDF",
    tagline: "Rewrite the file for smaller, cleaner output.",
    description: "Rebuilds the document with object streams. For image-heavy files it can also recompress pages.",
    category: "compress-pdf",
    icon: "Sparkle",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "quality", label: "Optimization", type: "select", defaultValue: "high", options: [{ value: "high", label: "Keep more detail" }, { value: "medium", label: "Balanced" }, { value: "low", label: "Smallest" }] }],
    related: ["compress-pdf", "repair-pdf"],
    nextActions: ["protect-pdf", "sign-pdf"],
    phrases: ["optimize pdf", "clean pdf"],
    howTo: ["Upload.", "Choose how aggressive to be.", "Download the optimized file."],
    faqs: [{ q: "Is optimize the same as compress?", a: "It uses the same engine with a gentler default. Compress is the better search term for shrinking scans." }],
    guide: { title: "How to optimize a PDF", paragraphs: ["Run optimize after merging several exports that each carry extra metadata.", privacy] },
  }),
  t({
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    h1: "Convert JPG to PDF",
    tagline: "Turn photos into a single PDF.",
    description: "Phone pictures of IDs, receipts and worksheets become a document you can upload anywhere that wants PDF.",
    category: "convert-pdf",
    icon: "Image",
    accepts: ["jpg"],
    multiple: true,
    output: "pdf",
    popular: true,
    local: true,
    settings: [],
    related: ["png-to-pdf", "merge-pdf", "compress-pdf", "pdf-to-jpg"],
    nextActions: ["merge-pdf", "compress-pdf", "pdf-page-numbering"],
    phrases: ["turn this picture into a pdf", "jpg to pdf", "photo to pdf", "image to pdf"],
    howTo: ["Add one or more JPG files.", "Each image becomes a page.", "Download the PDF, then compress if needed."],
    faqs: [{ q: "Will the PDF be huge?", a: "Photos make large PDFs. Convert first, then compress for the portal's limit." }],
    guide: { title: "How to convert JPG to PDF", paragraphs: ["This is the usual first step in an application workflow: photos → PDF → merge → compress.", privacy] },
  }),
  t({
    slug: "png-to-pdf",
    name: "PNG to PDF",
    h1: "Convert PNG to PDF",
    tagline: "Place PNG screenshots and graphics into a PDF.",
    description: "Keeps PNG pixels as pages. Screenshots of dashboards and signed forms land at their native size.",
    category: "convert-pdf",
    icon: "ImagePlus",
    accepts: ["png"],
    multiple: true,
    output: "pdf",
    local: true,
    settings: [],
    related: ["jpg-to-pdf", "webp-to-pdf", "merge-pdf"],
    nextActions: ["merge-pdf", "compress-pdf"],
    phrases: ["png to pdf", "screenshot to pdf"],
    howTo: ["Add PNG files.", "Process.", "Download."],
    faqs: [{ q: "Are transparent PNGs supported?", a: "Yes. Transparency is flattened against white when a processor requires it." }],
    guide: { title: "How to convert PNG to PDF", paragraphs: ["Use PNG for screenshots with text; JPG for camera photos.", privacy] },
  }),
  t({
    slug: "webp-to-pdf",
    name: "WebP to PDF",
    h1: "Convert WebP to PDF",
    tagline: "Browser images into a PDF.",
    description: "WebP files are rasterized in the browser, then placed as PDF pages.",
    category: "convert-pdf",
    icon: "Images",
    accepts: ["webp"],
    multiple: true,
    output: "pdf",
    local: true,
    settings: [],
    related: ["jpg-to-pdf", "png-to-pdf"],
    nextActions: ["compress-pdf", "merge-pdf"],
    phrases: ["webp to pdf"],
    howTo: ["Add WebP images.", "Process in the browser.", "Download the PDF."],
    faqs: [{ q: "Why WebP?", a: "Many phones now share WebP. Portals still want PDF." }],
    guide: { title: "How to convert WebP to PDF", paragraphs: ["Conversion happens locally by drawing the image, then embedding it.", privacy] },
  }),
  t({
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    h1: "Convert PDF to JPG",
    tagline: "Export each page as a JPEG image.",
    description: "Useful when a form wants photos, or you need to paste a page into a slide or chat.",
    category: "convert-pdf",
    icon: "FileImage",
    accepts: ["pdf"],
    multiple: false,
    output: "zip",
    popular: true,
    local: true,
    settings: [],
    related: ["pdf-to-png", "jpg-to-pdf", "compress-pdf"],
    nextActions: ["jpg-to-pdf", "compress-pdf"],
    phrases: ["pdf to image", "pdf to jpg", "save pdf as photo"],
    howTo: ["Upload a PDF.", "Each page is rendered.", "Download a ZIP if there are several pages."],
    faqs: [{ q: "What resolution is used?", a: "Pages render at 2× for a balance of sharpness and size." }],
    guide: { title: "How to convert PDF to JPG", paragraphs: ["If you only need one page, extract it first so the ZIP isn't full of extras.", privacy] },
  }),
  t({
    slug: "pdf-to-png",
    name: "PDF to PNG",
    h1: "Convert PDF to PNG",
    tagline: "Export pages as PNG.",
    description: "Prefer PNG when the page is mostly text or UI, and you want fewer JPEG artifacts.",
    category: "convert-pdf",
    icon: "FileImage",
    accepts: ["pdf"],
    multiple: false,
    output: "zip",
    local: true,
    settings: [],
    related: ["pdf-to-jpg", "pdf-to-webp"],
    nextActions: ["png-to-pdf", "compress-pdf"],
    phrases: ["pdf to png"],
    howTo: ["Upload.", "Render pages.", "Download PNG or ZIP."],
    faqs: [{ q: "Is PNG larger than JPG?", a: "Usually yes. Use JPG for photos, PNG for diagrams." }],
    guide: { title: "How to convert PDF to PNG", paragraphs: ["Designers often want PNG page exports for mockups.", privacy] },
  }),
  t({
    slug: "pdf-to-webp",
    name: "PDF to WebP",
    h1: "Convert PDF to WebP",
    tagline: "Export pages as WebP images.",
    description: "Smaller than PNG for many pages. Support depends on your browser's encoder.",
    category: "convert-pdf",
    icon: "FileImage",
    accepts: ["pdf"],
    multiple: false,
    output: "zip",
    local: true,
    settings: [],
    related: ["pdf-to-jpg", "pdf-to-png"],
    nextActions: ["webp-to-pdf"],
    phrases: ["pdf to webp"],
    howTo: ["Upload a PDF.", "Process.", "Download WebP files."],
    faqs: [{ q: "What if my browser can't encode WebP?", a: "You'll see an error. Use PDF to JPG instead." }],
    guide: { title: "How to convert PDF to WebP", paragraphs: ["WebP is handy for web teams who already standardized on it.", privacy] },
  }),
  t({
    slug: "word-to-pdf",
    name: "Word to PDF",
    h1: "Convert Word to PDF",
    tagline: "Turn a .docx into a readable PDF.",
    description: "Extracts text from Word and lays it into a clean PDF. Complex layout, headers and embedded objects are not reproduced pixel-perfect.",
    category: "convert-pdf",
    icon: "FileType",
    accepts: ["word"],
    multiple: false,
    output: "pdf",
    popular: true,
    local: true,
    settings: [],
    related: ["pdf-to-word", "compress-pdf", "pdf-page-numbering"],
    nextActions: ["compress-pdf", "pdf-page-numbering", "watermark-pdf"],
    phrases: ["docx to pdf", "word to pdf", "convert assignment"],
    howTo: ["Upload a .docx file.", "Text is placed into a PDF.", "Download, then number or compress."],
    faqs: [{ q: "Will my fonts look the same?", a: "No. This path is for readable text, not desktop publishing. Keep a print-to-PDF from Word when layout is the product." }],
    guide: { title: "How to convert Word to PDF", paragraphs: ["Students often need PDF for submissions. Convert, add page numbers, then compress for the LMS cap.", privacy] },
  }),
  t({
    slug: "pdf-to-word",
    name: "PDF to Word",
    h1: "Convert PDF to Word",
    tagline: "Make an editable .docx from PDF text.",
    description: "Pulls extractable text into a Word file. Scanned PDFs need OCR first. Layout will not match the original.",
    category: "convert-pdf",
    icon: "FileType2",
    accepts: ["pdf"],
    multiple: false,
    output: "office",
    popular: true,
    local: true,
    settings: [],
    related: ["ocr-pdf", "pdf-to-text", "word-to-pdf"],
    nextActions: ["ocr-pdf", "compress-pdf", "word-to-pdf"],
    phrases: ["pdf to docx", "edit pdf in word"],
    howTo: ["Upload a PDF.", "If it's a scan, run OCR first.", "Download the .docx."],
    faqs: [{ q: "Why is my Word file empty?", a: "The PDF is probably a scan. Use OCR PDF, then convert." }],
    guide: { title: "How to convert PDF to Word", paragraphs: ["This is a text recovery tool. It is not Adobe's layout-preserving export.", privacy] },
  }),
  t({
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    h1: "Convert Excel to PDF",
    tagline: "Put a spreadsheet into a landscape PDF.",
    description: "Reads the first sheet and draws rows as text. Charts and macros are not rendered.",
    category: "convert-pdf",
    icon: "Sheet",
    accepts: ["excel"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [],
    related: ["pdf-to-excel", "compress-pdf"],
    nextActions: ["compress-pdf", "protect-pdf"],
    phrases: ["xlsx to pdf", "spreadsheet to pdf"],
    howTo: ["Upload .xlsx.", "The first sheet is exported.", "Download the PDF."],
    faqs: [{ q: "Multiple sheets?", a: "Only the first sheet in this version. Split workbooks first if needed." }],
    guide: { title: "How to convert Excel to PDF", paragraphs: ["Use this for a quick printable dump, not a board-ready formatted report.", privacy] },
  }),
  t({
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    h1: "Convert PDF to Excel",
    tagline: "Dump PDF text into a spreadsheet.",
    description: "Lines become rows. Columns are guessed from extra spaces. Always verify numbers.",
    category: "convert-pdf",
    icon: "Table",
    accepts: ["pdf"],
    multiple: false,
    output: "office",
    local: true,
    settings: [],
    related: ["extract-tables", "pdf-to-text"],
    nextActions: ["extract-tables", "ocr-pdf"],
    phrases: ["pdf to xlsx", "pdf table to excel"],
    howTo: ["Upload a PDF.", "Process.", "Open the spreadsheet and check columns."],
    faqs: [{ q: "Will invoices line up?", a: "Sometimes. Extract Tables uses the same heuristics. Scanned invoices need OCR first." }],
    guide: { title: "How to convert PDF to Excel", paragraphs: ["Treat the result as a starting point, not a source of truth for accounting.", privacy] },
  }),
  t({
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    h1: "Convert PowerPoint to PDF",
    tagline: "Export slide text into a PDF.",
    description: "Reads .pptx slide text. Decorations, animations and precise layout are not kept.",
    category: "convert-pdf",
    icon: "Presentation",
    accepts: ["ppt"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [],
    related: ["pdf-to-powerpoint", "pdf-to-text"],
    nextActions: ["compress-pdf", "watermark-pdf"],
    phrases: ["pptx to pdf"],
    howTo: ["Upload a .pptx file.", "Slide text is collected.", "Download a text PDF."],
    faqs: [{ q: "Can I keep slide design?", a: "Not in this path. Export PDF from PowerPoint when design is required." }],
    guide: { title: "How to convert PowerPoint to PDF", paragraphs: ["This is for readable handouts of slide copy, not speaker-ready visuals.", privacy] },
  }),
  t({
    slug: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    h1: "Convert PDF to PowerPoint",
    tagline: "Each PDF page becomes a slide image.",
    description: "Pages are rasterized and placed on slides. Text on those slides is not editable.",
    category: "convert-pdf",
    icon: "Projector",
    accepts: ["pdf"],
    multiple: false,
    output: "office",
    local: true,
    settings: [],
    related: ["pdf-to-jpg", "powerpoint-to-pdf"],
    nextActions: ["pdf-to-jpg", "compress-pdf"],
    phrases: ["pdf to pptx", "pdf to slides"],
    howTo: ["Upload a PDF.", "Pages render to images.", "Download a .pptx."],
    faqs: [{ q: "Can I edit the words on the slide?", a: "No. You get pictures of pages. Use PDF to Word if you need text." }],
    guide: { title: "How to convert PDF to PowerPoint", paragraphs: ["Useful when you must drop a PDF into a deck quickly.", privacy] },
  }),
  t({
    slug: "pdf-to-text",
    name: "PDF to text",
    h1: "Extract text from a PDF",
    tagline: "Plain text, no layout.",
    description: "Copies extractable text. For scans, use OCR PDF instead.",
    category: "convert-pdf",
    icon: "FileText",
    accepts: ["pdf"],
    multiple: false,
    output: "text",
    local: true,
    settings: [],
    related: ["extract-text", "ocr-pdf", "pdf-to-word"],
    nextActions: ["ocr-pdf", "pdf-summarizer"],
    phrases: ["copy text from pdf", "pdf to txt"],
    howTo: ["Upload.", "Extract.", "Download a .txt file."],
    faqs: [{ q: "Why is text jumbled?", a: "Some PDFs store glyphs out of reading order. OCR can be more reliable on those files." }],
    guide: { title: "How to extract PDF text", paragraphs: ["Use this for search, quotes and accessibility drafts.", privacy] },
  }),
  t({
    slug: "edit-pdf",
    name: "Edit PDF",
    h1: "Edit a PDF",
    tagline: "Add overlay text to your document.",
    description: "A practical editor for captions, notes and corrections. It stamps text onto pages rather than rewriting the original layout engine.",
    category: "edit-pdf",
    icon: "PenLine",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    popular: true,
    local: true,
    settings: [
      { key: "text", label: "Text to add", type: "textarea", placeholder: "Approved — 16 Sep 2026" },
      { key: "size", label: "Size", type: "number", defaultValue: "14" },
      { key: "x", label: "Horizontal position %", type: "number", defaultValue: "12" },
      { key: "y", label: "Vertical position %", type: "number", defaultValue: "88" },
      { key: "pages", label: "Pages", type: "text", placeholder: "All if empty" },
    ],
    related: ["add-text", "watermark-pdf", "sign-pdf", "add-image"],
    nextActions: ["sign-pdf", "watermark-pdf", "protect-pdf"],
    phrases: ["edit pdf", "write on pdf", "annotate pdf"],
    howTo: ["Upload a PDF.", "Enter overlay text and position.", "Download the edited file."],
    faqs: [{ q: "Can I change existing sentences?", a: "Not as a word processor. You add a new layer. For full rewrite, extract text or convert to Word." }],
    guide: { title: "How to edit a PDF", paragraphs: ["Most everyday edits are stamps: a date, a name, a note. That's what this tool does well.", privacy] },
  }),
  t({
    slug: "add-text",
    name: "Add text",
    h1: "Add text to a PDF",
    tagline: "Stamp a line or paragraph onto pages.",
    description: "Faster than the general editor when you only need text.",
    category: "edit-pdf",
    icon: "Type",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [
      { key: "text", label: "Text", type: "textarea", placeholder: "Your note" },
      { key: "size", label: "Size", type: "number", defaultValue: "14" },
      { key: "pages", label: "Pages", type: "text" },
    ],
    related: ["edit-pdf", "add-header", "watermark-pdf"],
    nextActions: ["sign-pdf", "protect-pdf"],
    phrases: ["add text to pdf", "type on pdf"],
    howTo: ["Upload.", "Type the text.", "Download."],
    faqs: [{ q: "Can I pick a font?", a: "This version uses a built-in Helvetica for reliability." }],
    guide: { title: "How to add text to a PDF", paragraphs: ["Use a short line for stamps. Long essays belong in Word, then Word to PDF.", privacy] },
  }),
  t({
    slug: "add-image",
    name: "Add image",
    h1: "Add an image to a PDF",
    tagline: "Stamp a PNG or JPG onto selected pages.",
    description: "Place a logo, stamp or photo. Upload the PDF plus the image.",
    category: "edit-pdf",
    icon: "ImagePlus",
    accepts: ["pdf", "image"],
    multiple: true,
    extraImage: true,
    output: "pdf",
    local: true,
    settings: [{ key: "pages", label: "Pages", type: "text", defaultValue: "1" }],
    related: ["watermark-pdf", "sign-pdf", "jpg-to-pdf"],
    nextActions: ["watermark-pdf", "protect-pdf"],
    phrases: ["stamp logo", "add picture to pdf"],
    howTo: ["Add a PDF and an image.", "Choose pages.", "Download."],
    faqs: [{ q: "Where does the image land?", a: "Top-left with a practical default size. Fine placement can follow in a later editor pass." }],
    guide: { title: "How to add an image to a PDF", paragraphs: ["Keep logos as PNG. Photos as JPG.", privacy] },
  }),
  t({
    slug: "draw-on-pdf",
    name: "Draw",
    h1: "Draw on a PDF",
    tagline: "Add a simple box mark.",
    description: "Places a rectangular outline so you can highlight a region. Not a freehand illustration studio.",
    category: "edit-pdf",
    icon: "Pencil",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "pages", label: "Pages", type: "text" }],
    related: ["highlight-pdf", "add-shapes", "sign-pdf"],
    nextActions: ["highlight-pdf", "sign-pdf"],
    phrases: ["draw on pdf", "box on pdf"],
    howTo: ["Upload.", "Process to add a box.", "Download."],
    faqs: [{ q: "Freehand pen?", a: "Not in this version. Use Highlight or Shapes for quick marks." }],
    guide: { title: "How to draw on a PDF", paragraphs: ["Meant for a visible frame around a clause, not artwork.", privacy] },
  }),
  t({
    slug: "highlight-pdf",
    name: "Highlight",
    h1: "Highlight a PDF",
    tagline: "Add a translucent yellow band.",
    description: "Marks a horizontal region. Adjust the vertical position as a percentage.",
    category: "edit-pdf",
    icon: "Highlighter",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [
      { key: "y", label: "Vertical position %", type: "number", defaultValue: "70" },
      { key: "pages", label: "Pages", type: "text" },
    ],
    related: ["draw-on-pdf", "add-text"],
    nextActions: ["add-text", "sign-pdf"],
    phrases: ["highlight pdf", "marker on pdf"],
    howTo: ["Upload.", "Set position.", "Download."],
    faqs: [{ q: "Can I highlight a word exactly?", a: "This stamps a band. Precise word highlight needs a full annotation suite — planned, not faked." }],
    guide: { title: "How to highlight a PDF", paragraphs: ["Use it to mark a signature line or a fee table before you send a draft.", privacy] },
  }),
  t({
    slug: "add-shapes",
    name: "Add shapes",
    h1: "Add shapes to a PDF",
    tagline: "Place a rectangle outline on the page.",
    description: "A simple shape layer for callouts. Not a diagram editor.",
    category: "edit-pdf",
    icon: "Square",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "pages", label: "Pages", type: "text" }],
    related: ["draw-on-pdf", "highlight-pdf"],
    nextActions: ["add-text", "watermark-pdf"],
    phrases: ["rectangle on pdf", "shape overlay"],
    howTo: ["Upload.", "Process.", "Download."],
    faqs: [{ q: "Circles and arrows?", a: "Not yet. Rectangle outlines ship first because they are reliable." }],
    guide: { title: "How to add shapes", paragraphs: ["Pair a box with Add Text for a cheap callout.", privacy] },
  }),
  t({
    slug: "sign-pdf",
    name: "Sign PDF",
    h1: "Sign a PDF",
    tagline: "Add a typed signature line.",
    description: "Places a name in italic with an underline. This is a visual signature, not a government eID or certificate-based digital signature.",
    category: "pdf-security",
    icon: "Signature",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    popular: true,
    local: true,
    settings: [{ key: "text", label: "Signature name", type: "text", placeholder: "Your name", defaultValue: "Signed" }, { key: "pages", label: "Pages", type: "text", placeholder: "Last page if empty", defaultValue: "" }],
    related: ["add-signature", "protect-pdf", "watermark-pdf"],
    nextActions: ["protect-pdf", "watermark-pdf", "compress-pdf"],
    phrases: ["sign document", "add signature", "sign pdf"],
    howTo: ["Upload the PDF.", "Type the name to appear.", "Download the signed file, then protect it if needed."],
    faqs: [{ q: "Is this legally binding?", a: "That depends on your jurisdiction and the other party. This tool does not create a cryptographic digital signature." }],
    guide: { title: "How to sign a PDF", paragraphs: ["For many landlords and schools, a typed name on the signature line is what they asked for. Follow with Protect PDF if the file should not be edited casually.", privacy] },
  }),
  t({
    slug: "add-signature",
    name: "Add signature",
    h1: "Add a signature",
    tagline: "Same visual signature, search-friendly URL.",
    description: "Identical processor to Sign PDF.",
    category: "edit-pdf",
    icon: "PenTool",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "text", label: "Signature name", type: "text", defaultValue: "Signed" }],
    related: ["sign-pdf", "add-image"],
    nextActions: ["protect-pdf", "compress-pdf"],
    phrases: ["signature stamp"],
    howTo: ["Upload.", "Enter a name.", "Download."],
    faqs: [{ q: "Upload a handwritten PNG?", a: "Use Add Image for a photo of your signature." }],
    guide: { title: "How to add a signature", paragraphs: ["Typed for speed, image for a pen look.", privacy] },
  }),
  t({
    slug: "watermark-pdf",
    name: "Watermark PDF",
    h1: "Add a watermark to a PDF",
    tagline: "Mark drafts, copies and client files.",
    description: "Draws a large diagonal label such as CONFIDENTIAL or DRAFT across selected pages.",
    category: "edit-pdf",
    icon: "Stamp",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [
      { key: "text", label: "Watermark text", type: "text", defaultValue: "CONFIDENTIAL" },
      { key: "opacity", label: "Opacity (0.1–0.5)", type: "number", defaultValue: "0.22" },
    ],
    related: ["protect-pdf", "sign-pdf", "add-header"],
    nextActions: ["sign-pdf", "protect-pdf", "compress-pdf"],
    phrases: ["draft watermark", "confidential stamp"],
    howTo: ["Upload.", "Set the label.", "Download."],
    faqs: [{ q: "Can someone remove it?", a: "A determined editor can. Pair watermarking with Protect PDF when you need a password as well." }],
    guide: { title: "How to watermark a PDF", paragraphs: ["Business packets often go watermark → sign → protect before they leave the laptop.", privacy] },
  }),
  t({
    slug: "add-header",
    name: "Add header",
    h1: "Add a header to a PDF",
    tagline: "A line of text at the top of every page.",
    description: "Company name, matter number or 'Not for distribution'.",
    category: "edit-pdf",
    icon: "PanelTop",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "text", label: "Header text", type: "text", defaultValue: "Document" }],
    related: ["add-footer", "pdf-page-numbering", "watermark-pdf"],
    nextActions: ["add-footer", "pdf-page-numbering"],
    phrases: ["pdf header", "letterhead line"],
    howTo: ["Upload.", "Enter header text.", "Download."],
    faqs: [{ q: "Will it cover existing headers?", a: "It draws on top. Leave the original, or delete pages that already have a header." }],
    guide: { title: "How to add a PDF header", paragraphs: ["Keep it short. Long headers collide with bound documents.", privacy] },
  }),
  t({
    slug: "add-footer",
    name: "Add footer",
    h1: "Add a footer to a PDF",
    tagline: "A line of text at the bottom of every page.",
    description: "Use for disclaimers, version labels or 'Page preview'.",
    category: "edit-pdf",
    icon: "PanelBottom",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "text", label: "Footer text", type: "text", defaultValue: "Confidential" }],
    related: ["add-header", "pdf-page-numbering"],
    nextActions: ["pdf-page-numbering", "protect-pdf"],
    phrases: ["pdf footer", "disclaimer line"],
    howTo: ["Upload.", "Enter footer text.", "Download."],
    faqs: [{ q: "Footer plus page numbers?", a: "Add the footer first, then page numbers on a different position such as bottom-right." }],
    guide: { title: "How to add a PDF footer", paragraphs: ["Version strings in the footer save awkward 'which file is this' email threads.", privacy] },
  }),
  t({
    slug: "protect-pdf",
    name: "Protect PDF",
    h1: "Protect a PDF with a password",
    tagline: "Encrypt the file so opening it requires a password.",
    description: "Uses real AES-256 PDF encryption. Remember the password — we cannot reset it.",
    category: "pdf-security",
    icon: "Lock",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    popular: true,
    local: true,
    settings: [{ key: "password", label: "Password", type: "password", placeholder: "At least 4 characters" }],
    related: ["unlock-pdf", "encrypt-pdf", "watermark-pdf", "sign-pdf"],
    nextActions: ["watermark-pdf", "sign-pdf"],
    phrases: ["password protect pdf", "lock pdf", "encrypt pdf"],
    howTo: ["Upload a PDF.", "Choose a password.", "Download the encrypted file."],
    faqs: [{ q: "What if I forget the password?", a: "Nobody can recover it from this site. Unlock only works when you still know the password." }],
    guide: { title: "How to protect a PDF", paragraphs: ["Encryption happens locally. Send the password through a different channel than the file.", privacy] },
  }),
  t({
    slug: "encrypt-pdf",
    name: "Encrypt PDF",
    h1: "Encrypt a PDF",
    tagline: "AES-256 encryption with a user password.",
    description: "Same engine as Protect PDF, labeled for people who search 'encrypt'.",
    category: "pdf-security",
    icon: "KeyRound",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "password", label: "Password", type: "password" }],
    related: ["protect-pdf", "decrypt-pdf"],
    nextActions: ["watermark-pdf"],
    phrases: ["encrypt pdf aes"],
    howTo: ["Upload.", "Set a password.", "Download."],
    faqs: [{ q: "Owner vs user password?", a: "This version sets both to the same value so the file simply won't open without it." }],
    guide: { title: "How to encrypt a PDF", paragraphs: ["Encryption is not hiding — it is locking. Share the key separately.", privacy] },
  }),
  t({
    slug: "add-password",
    name: "Add password",
    h1: "Add a password to a PDF",
    tagline: "Require a password to open the file.",
    description: "Identical encryption path with copy aimed at 'add password' searches.",
    category: "pdf-security",
    icon: "LockKeyhole",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "password", label: "Password", type: "password" }],
    related: ["protect-pdf", "remove-password"],
    nextActions: ["sign-pdf"],
    phrases: ["add password to pdf"],
    howTo: ["Upload.", "Password.", "Download."],
    faqs: [{ q: "Does this upload my password?", a: "No. Encryption runs in the browser." }],
    guide: { title: "How to add a PDF password", paragraphs: ["Use a password you can actually type on a phone — many recipients open files on mobile.", privacy] },
  }),
  t({
    slug: "unlock-pdf",
    name: "Unlock PDF",
    h1: "Unlock a PDF",
    tagline: "Remove a password when you are allowed to.",
    description: "Provide the existing password. We write an unprotected copy. We will not bypass passwords you do not have.",
    category: "pdf-security",
    icon: "Unlock",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "password", label: "Current password", type: "password" }],
    related: ["decrypt-pdf", "remove-password", "protect-pdf"],
    nextActions: ["compress-pdf", "pdf-to-word", "edit-pdf"],
    phrases: ["remove pdf password", "unlock pdf", "decrypt pdf"],
    howTo: ["Upload the protected PDF.", "Enter the password that already opens it.", "Download the unlocked copy."],
    faqs: [{ q: "Can you crack unknown passwords?", a: "No. That would be unauthorized access. Unlock only works with the real password." }],
    guide: { title: "How to unlock a PDF", paragraphs: ["People unlock files they encrypted themselves so a school portal can ingest the document.", privacy] },
  }),
  t({
    slug: "decrypt-pdf",
    name: "Decrypt PDF",
    h1: "Decrypt a PDF",
    tagline: "Authorized decryption with the file password.",
    description: "Same rules as Unlock PDF.",
    category: "pdf-security",
    icon: "ShieldOff",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "password", label: "Password", type: "password" }],
    related: ["unlock-pdf", "encrypt-pdf"],
    nextActions: ["edit-pdf", "compress-pdf"],
    phrases: ["decrypt pdf"],
    howTo: ["Upload.", "Password.", "Download."],
    faqs: [{ q: "Wrong password?", a: "You'll get a clear error. Try the owner password if you set two." }],
    guide: { title: "How to decrypt a PDF", paragraphs: ["Keep the encrypted original. Decrypt a working copy.", privacy] },
  }),
  t({
    slug: "remove-password",
    name: "Remove password",
    h1: "Remove a PDF password",
    tagline: "Strip protection with authorization.",
    description: "Requires the current password. No brute force, no 'master keys'.",
    category: "pdf-security",
    icon: "Unlink",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "password", label: "Current password", type: "password" }],
    related: ["unlock-pdf", "add-password"],
    nextActions: ["compress-pdf", "merge-pdf"],
    phrases: ["remove password from pdf"],
    howTo: ["Upload.", "Enter the password.", "Download an open file."],
    faqs: [{ q: "Is this legal?", a: "Only use it on files you are allowed to open. The product will not help bypass unknown passwords." }],
    guide: { title: "How to remove a PDF password", paragraphs: ["Common when a bank sends a protected PDF and a website refuses encrypted uploads.", privacy] },
  }),
  t({
    slug: "fill-pdf",
    name: "Fill PDF",
    h1: "Fill a PDF form",
    tagline: "Write into existing AcroForm fields.",
    description: "If the PDF has real form fields, we fill text fields and flatten them. If it is a flat scan, use Add Text instead.",
    category: "pdf-forms",
    icon: "ClipboardPen",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "value", label: "Text for all text fields", type: "text", placeholder: "Your answer" }],
    related: ["create-pdf-form", "add-text", "sign-pdf"],
    nextActions: ["sign-pdf", "protect-pdf"],
    phrases: ["fillable pdf", "complete form"],
    howTo: ["Upload a fillable PDF.", "Enter a value to apply to text fields.", "Download a flattened copy."],
    faqs: [{ q: "Why 'no fields'?", a: "Many 'forms' are just drawn lines. Those need Add Text, not Fill PDF." }],
    guide: { title: "How to fill a PDF form", paragraphs: ["This version applies one value across text fields so you can verify the form is live. A full field-by-field inspector is the next iteration.", privacy] },
  }),
  t({
    slug: "create-pdf-form",
    name: "Create PDF form",
    h1: "Create a basic fillable PDF form",
    tagline: "Add name and email fields to a page.",
    description: "A starting form, not a full form designer. Download and open in a PDF reader that supports fields.",
    category: "pdf-forms",
    icon: "ListChecks",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [],
    related: ["fill-pdf", "add-text"],
    nextActions: ["fill-pdf", "protect-pdf"],
    phrases: ["make fillable pdf", "create form"],
    howTo: ["Upload a PDF (or a one-page file).", "Name and email fields are added.", "Download."],
    faqs: [{ q: "Custom fields?", a: "Not in this slice. The architecture is ready for more field types." }],
    guide: { title: "How to create a fillable PDF", paragraphs: ["Use this for a lightweight intake sheet, then Fill PDF to test it.", privacy] },
  }),
  t({
    slug: "ocr-pdf",
    name: "OCR PDF",
    h1: "OCR a PDF",
    tagline: "Read text from scans on your device.",
    description: "Tesseract runs in the browser. English is the default language pack. Handwriting and tiny scans will misread — we say so.",
    category: "ocr-pdf",
    icon: "ScanText",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "pages", label: "Pages", type: "text", defaultValue: "1", help: "OCR is slow. Start with one page." }],
    related: ["extract-text", "pdf-to-word", "pdf-summarizer"],
    nextActions: ["pdf-to-word", "pdf-summarizer", "pdf-to-text"],
    phrases: ["scan to text", "ocr pdf", "readable scan"],
    howTo: ["Upload a scanned PDF.", "Choose a page range.", "Wait for OCR, then download a text PDF."],
    faqs: [{ q: "Why so slow?", a: "OCR is heavy. That's why it stays on one device and why we suggest a page range." }],
    guide: { title: "How to OCR a PDF", paragraphs: ["Run OCR on the page you care about, then convert that text PDF to Word if you need editing.", privacy] },
  }),
  t({
    slug: "extract-text",
    name: "Extract text",
    h1: "Extract text from a PDF",
    tagline: "Plain text without converting formats.",
    description: "Companion to PDF to text, aimed at 'extract' searches.",
    category: "ocr-pdf",
    icon: "TextSelect",
    accepts: ["pdf"],
    multiple: false,
    output: "text",
    local: true,
    settings: [],
    related: ["pdf-to-text", "ocr-pdf", "extract-tables"],
    nextActions: ["pdf-summarizer", "ocr-pdf"],
    phrases: ["extract text from pdf"],
    howTo: ["Upload.", "Extract.", "Download .txt."],
    faqs: [{ q: "Scanned file?", a: "Use OCR PDF first." }],
    guide: { title: "How to extract text", paragraphs: ["Good for quotes, research notes and feeding a summarizer.", privacy] },
  }),
  t({
    slug: "extract-images",
    name: "Extract images",
    h1: "Extract images from a PDF",
    tagline: "Save each page as a PNG.",
    description: "Page-based export. It does not promise to unpack every embedded photo from a mixed magazine layout.",
    category: "ocr-pdf",
    icon: "Images",
    accepts: ["pdf"],
    multiple: false,
    output: "zip",
    local: true,
    settings: [],
    related: ["pdf-to-png", "pdf-to-jpg"],
    nextActions: ["jpg-to-pdf", "png-to-pdf"],
    phrases: ["pull images from pdf"],
    howTo: ["Upload.", "Render pages.", "Download a ZIP of PNGs."],
    faqs: [{ q: "Why pages not assets?", a: "Reliable page export ships first. Deep XObject mining is a later engine." }],
    guide: { title: "How to extract images", paragraphs: ["If you need a photo that fills a page, this is enough. For many small logos, crop the PNG.", privacy] },
  }),
  t({
    slug: "extract-tables",
    name: "Extract tables",
    h1: "Extract tables from a PDF",
    tagline: "Heuristic rows into Excel.",
    description: "Splits lines on wide gaps. Always audit numbers. Not a guaranteed table parser.",
    category: "ocr-pdf",
    icon: "Table2",
    accepts: ["pdf"],
    multiple: false,
    output: "office",
    local: true,
    settings: [],
    related: ["pdf-to-excel", "ocr-pdf"],
    nextActions: ["pdf-to-excel", "ocr-pdf"],
    phrases: ["pdf table", "extract table"],
    howTo: ["Upload.", "Process.", "Check the spreadsheet."],
    faqs: [{ q: "Bordered tables?", a: "Borders are ignored. Spacing is the clue. OCR if the table is a picture." }],
    guide: { title: "How to extract tables", paragraphs: ["Start here, then clean columns in Excel. Don't wire this into payroll without a human check.", privacy] },
  }),
  t({
    slug: "pdf-summarizer",
    name: "PDF summarizer",
    h1: "Summarize a PDF",
    tagline: "On-device extractive summary.",
    description: "Scores sentences from the file you uploaded. Labeled as AI-assisted, not guaranteed accurate. Cloud models are optional later.",
    category: "ai-pdf-tools",
    icon: "Sparkles",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [],
    related: ["ask-pdf", "extract-text", "ocr-pdf"],
    nextActions: ["ask-pdf", "pdf-to-word"],
    phrases: ["summarize pdf", "tl;dr pdf", "key points"],
    howTo: ["Upload a text PDF.", "We extract and rank sentences.", "Download a summary PDF."],
    faqs: [{ q: "Is this ChatGPT?", a: "No. It is extractive, local, and honest. Plug in an AI key later for generative summaries." }],
    guide: { title: "How to summarize a PDF", paragraphs: ["Works best on reports with real text. OCR scans first.", privacy] },
  }),
  t({
    slug: "ask-pdf",
    name: "Ask questions about a PDF",
    h1: "Ask questions about a PDF",
    tagline: "Find sentences that match your question.",
    description: "Keyword retrieval over extracted text. Not a hallucinating chatbot. Answers are labeled as retrieved.",
    category: "ai-pdf-tools",
    icon: "MessageCircleQuestion",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [{ key: "question", label: "Question", type: "textarea", placeholder: "What is the deadline?" }],
    related: ["pdf-summarizer", "extract-text"],
    nextActions: ["pdf-summarizer", "extract-text"],
    phrases: ["ask pdf", "question this document"],
    howTo: ["Upload.", "Ask a question using words from the file.", "Read the retrieved sentences."],
    faqs: [{ q: "Why a weak answer?", a: "Your question may not share words with the PDF. Quote a phrase from the document." }],
    guide: { title: "How to ask a PDF a question", paragraphs: ["This is search, not advice. Read the surrounding page before you act.", privacy] },
  }),
  t({
    slug: "translate-pdf",
    name: "Translate PDF",
    h1: "Translate a PDF",
    tagline: "Requires a configured AI provider.",
    description: "Will not fake a translation. If no AI_API_KEY is configured, the tool explains how to enable it.",
    category: "ai-pdf-tools",
    icon: "Languages",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    premium: true,
    local: false,
    settings: [{ key: "target", label: "Target language", type: "select", defaultValue: "es", options: [{ value: "es", label: "Spanish" }, { value: "fr", label: "French" }, { value: "de", label: "German" }, { value: "pt", label: "Portuguese" }] }],
    related: ["extract-text", "ocr-pdf"],
    nextActions: ["extract-text", "ocr-pdf"],
    phrases: ["translate pdf"],
    howTo: ["Configure AI_API_KEY.", "Upload.", "Download a translated text PDF when the provider responds."],
    faqs: [{ q: "Why is it disabled?", a: "Translation needs a remote model. We refuse to pretend otherwise." }],
    guide: { title: "How to translate a PDF", paragraphs: ["Until a key is set, extract text and use your own translator. That is safer than a fake bilingual PDF.", privacy] },
  }),
  t({
    slug: "compare-pdfs",
    name: "Compare PDFs",
    h1: "Compare two PDFs",
    tagline: "Word-level text diff.",
    description: "Shows tokens that appear in only one file. Not a visual overlay of layout changes.",
    category: "ai-pdf-tools",
    icon: "GitCompare",
    accepts: ["pdf"],
    multiple: true,
    minFiles: 2,
    output: "pdf",
    local: true,
    settings: [],
    related: ["extract-text", "pdf-summarizer"],
    nextActions: ["extract-text", "watermark-pdf"],
    phrases: ["diff pdf", "compare contracts"],
    howTo: ["Add two PDFs.", "Process.", "Read the comparison PDF."],
    faqs: [{ q: "Pixel diff?", a: "Not in this version. This compares extractable words." }],
    guide: { title: "How to compare PDFs", paragraphs: ["Helpful for 'did this clause change' on text contracts. Useless on scans until OCR.", privacy] },
  }),
  t({
    slug: "repair-pdf",
    name: "Repair PDF",
    h1: "Repair a PDF",
    tagline: "Rebuild a stubborn file's pages.",
    description: "Copies pages into a new document and saves a clean structure. Completely unreadable files cannot be invented back into existence.",
    category: "document-tools",
    icon: "Wrench",
    accepts: ["pdf"],
    multiple: false,
    output: "pdf",
    local: true,
    settings: [],
    related: ["optimize-pdf", "unlock-pdf", "compress-pdf"],
    nextActions: ["compress-pdf", "unlock-pdf"],
    phrases: ["fix pdf", "repair pdf", "corrupt pdf"],
    howTo: ["Upload the damaged PDF.", "We rebuild the page tree.", "Try opening the download."],
    faqs: [{ q: "Still broken?", a: "The source may be truncated. Export again from the original app." }],
    guide: { title: "How to repair a PDF", paragraphs: ["Repair is a rewrite, not magic. It helps with some export glitches and leftover encryption flags.", privacy] },
  }),
];

const bySlug = new Map(TOOLS.map((tool) => [tool.slug, tool]));

export function getTool(slug: string): ToolDefinition | undefined {
  return bySlug.get(slug);
}

export function getCategory(slug: string) {
  return CATEGORIES.find((c) => c.slug === slug);
}

const CATEGORY_OVERRIDES: Record<string, string[]> = {
  "image-tools": ["jpg-to-pdf", "png-to-pdf", "webp-to-pdf", "pdf-to-jpg", "pdf-to-png", "pdf-to-webp", "extract-images", "add-image"],
  "document-tools": ["word-to-pdf", "pdf-to-word", "excel-to-pdf", "pdf-to-excel", "powerpoint-to-pdf", "pdf-to-powerpoint", "pdf-to-text", "repair-pdf"],
  "business-tools": ["watermark-pdf", "sign-pdf", "protect-pdf", "merge-pdf", "compress-pdf", "pdf-page-numbering", "unlock-pdf"],
};

export function toolsInCategory(slug: string): ToolDefinition[] {
  if (slug === "pdf-tools") return TOOLS;
  const override = CATEGORY_OVERRIDES[slug];
  if (override) return override.map((id) => bySlug.get(id)).filter((item): item is ToolDefinition => item != null);
  return TOOLS.filter((item) => item.category === slug);
}

export function popularTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.popular);
}

export function allSlugs(): string[] {
  return [...CATEGORIES.map((c) => c.slug), ...TOOLS.map((t) => t.slug)];
}

export type { ToolDefinition, CategoryDefinition, ToolSetting, Faq } from "@/lib/tools/types";
export { CATEGORIES };
